// Generated by Assemora. Do not edit: run `assemora sdk:generate` instead.

import { type Client, type ClientOptions, createClient, type ResourceClient } from './client.js'

export type BlogPosts = {
  readonly id: string
  readonly title: string
  readonly status?: 'draft' | 'published'
  readonly 'x-legacy-id'?: string
  readonly tags?: readonly ('news' | 'guide')[]
}
export type HelpArticles = {
  readonly id: string
  readonly body: string
}
/**
 * This application serves no REST endpoint for this resource, so the client has no
 * accessor for it: every call would have answered 404. Its entries are reachable
 * through the entries.* commands and queries.
 */
export type _2faTokens = {
  readonly id: string
  readonly code: string
}

export type Endpoints = {
  /** One report, rendered */
  getReportsById(input: {
    readonly params: {
      readonly id: string
    }
  }): Promise<{
    readonly 'content-type': string
    readonly rows?: readonly number[]
  }>
  getBlogPosts(): Promise<unknown>
  getBlogPostsById(): Promise<unknown>
  postBlogPosts(): Promise<unknown>
  patchBlogPostsById(): Promise<unknown>
  deleteBlogPostsById(): Promise<unknown>
  getHelpArticles(): Promise<unknown>
  getHelpArticlesById(): Promise<unknown>
}

export type AssemoraApi = Client & {
  readonly 'blog-posts': ResourceClient<BlogPosts>
  readonly 'help-articles': Pick<ResourceClient<HelpArticles>, 'list' | 'get'>
  readonly endpoints: Endpoints
}

export const createTypedClient = (options: ClientOptions): AssemoraApi =>
  createClient(options) as AssemoraApi
