import { describe, expect, it } from 'vitest'

import { generateSdk, toTypeScript } from './generate.js'

const snapshot = {
  resources: [
    {
      name: 'articles',
      label: 'Articles',
      fields: [
        { name: 'title', required: true, schema: { type: 'string' } },
        {
          name: 'status',
          required: false,
          schema: { type: 'string', enum: ['draft', 'published'] },
        },
        { name: 'views', required: false, schema: { type: 'number' } },
        { name: 'passwordHash', required: false, hidden: true, schema: { type: 'string' } },
      ],
    },
  ],
  routes: [
    {
      name: 'post /auth/login',
      method: 'post',
      path: '/auth/login',
      description: 'Exchanges credentials for a token',
      body: {
        type: 'object',
        properties: { email: { type: 'string' }, password: { type: 'string' } },
        required: ['email', 'password'],
      },
      response: { type: 'object', properties: { token: { type: 'string' } }, required: ['token'] },
    },
  ],
}

describe('JSON Schema as TypeScript', () => {
  it('maps the scalars', () => {
    expect(toTypeScript({ type: 'string' })).toBe('string')
    expect(toTypeScript({ type: 'number' })).toBe('number')
    expect(toTypeScript({ type: 'integer' })).toBe('number')
    expect(toTypeScript({ type: 'boolean' })).toBe('boolean')
    expect(toTypeScript(undefined)).toBe('unknown')
  })

  it('keeps an enum as a union of literals', () => {
    expect(toTypeScript({ type: 'string', enum: ['draft', 'published'] })).toBe(
      '"draft" | "published"',
    )
  })

  it('maps arrays and objects', () => {
    expect(toTypeScript({ type: 'array', items: { type: 'string' } })).toBe('readonly string[]')
    expect(
      toTypeScript({
        type: 'object',
        properties: { a: { type: 'string' }, b: { type: 'number' } },
        required: ['a'],
      }),
    ).toBe('{\n  readonly a: string\n  readonly b?: number\n}')
  })

  it('reads a date as what actually arrives: a string', () => {
    expect(toTypeScript({ type: 'string', format: 'date-time' })).toBe('string')
  })
})

describe('the emitted client', () => {
  const source = generateSdk(snapshot)

  it('declares a record type per resource', () => {
    expect(source).toContain('export type Articles = {')
    expect(source).toContain('  readonly id: string')
    expect(source).toContain('  readonly title: string')
    expect(source).toContain('  readonly status?: "draft" | "published"')
  })

  it('leaves hidden fields out of the client as well (SPEC.md §85)', () => {
    expect(source).not.toContain('passwordHash')
  })

  it('exposes each resource on the API type', () => {
    expect(source).toContain('readonly articles: ResourceClient<Articles>')
  })

  it('gives a custom route a method of its own (SPEC.md §121)', () => {
    expect(source).toContain('export type Endpoints = {')
    expect(source).toContain('/** Exchanges credentials for a token */')
    expect(source).toContain('postAuthLogin(input: {')
    expect(source).toContain('readonly token: string')
  })

  it('names the factory the application will call', () => {
    expect(source).toContain(
      'export const createTypedClient = (options: ClientOptions): AssemoraApi =>',
    )
  })

  it('says it is generated and must not be edited', () => {
    expect(source.split('\n')[0]).toContain('Generated by Assemora')
  })

  it('emits something usable even for an empty application', () => {
    const empty = generateSdk({})

    expect(empty).toContain('export type AssemoraApi = Client & {')
    expect(empty).not.toContain('undefined')
  })
})

describe('a type that has to be bracketed before it can be an array', () => {
  it('groups a union, which would otherwise bind to the last member alone', () => {
    expect(toTypeScript({ type: 'array', items: { enum: ['mobile', 'tablet'] } })).toBe(
      'readonly ("mobile" | "tablet")[]',
    )
  })

  it('groups an array of arrays, which TypeScript refuses ungrouped', () => {
    expect(
      toTypeScript({ type: 'array', items: { type: 'array', items: { type: 'string' } } }),
    ).toBe('readonly (readonly string[])[]')
  })

  it('leaves a plain element alone rather than bracketing every line', () => {
    expect(toTypeScript({ type: 'array', items: { type: 'string' } })).toBe('readonly string[]')
  })

  it('leaves an object literal alone, whatever its properties hold', () => {
    expect(
      toTypeScript({
        type: 'array',
        items: { type: 'object', properties: { size: { enum: ['sm', 'lg'] } } },
      }),
    ).toContain('readonly {')
  })
})
