// Generated by Assemora. Do not edit: run `assemora sdk:generate` instead.

import { type Client, type ClientOptions, createClient, type ResourceClient } from './client.js'

export type BlogPosts = {
  readonly id: string
  readonly title: string
  readonly status?: 'draft' | 'published'
  readonly 'x-legacy-id'?: string
  readonly tags?: readonly ('news' | 'guide')[]
}
export type HelpArticles = {
  readonly id: string
  readonly body: string
}
export type _2faTokens = {
  readonly id: string
  readonly code: string
}

export type Endpoints = {
  /** One report, rendered */
  getReportsById(input: {
    readonly params: {
      readonly id: string
    }
  }): Promise<{
    readonly 'content-type': string
    readonly rows?: readonly number[]
  }>
}

export type AssemoraApi = Client & {
  readonly 'blog-posts': ResourceClient<BlogPosts>
  readonly 'help-articles': ResourceClient<HelpArticles>
  readonly '2fa-tokens': ResourceClient<_2faTokens>
  readonly endpoints: Endpoints
}

export const createTypedClient = (options: ClientOptions): AssemoraApi =>
  createClient(options) as AssemoraApi
